name: speciesnet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - numpy
  - pandas
  - pillow
  - opencv
  - tqdm
  - pip:
      - git+https://github.com/google/cameratrapai.git

